version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: minimal-agent-postgres
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: minimal_agent_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-ALPINE", "pg_isready", "-U", "devuser", "-d", "minimal_agent_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: